### ISSUE TITLE
TAP/TUN 代码 可以正常工作吗？

### ISSUE THREAD

**Issue by LuoZijun** [realityone/akarin#6]
你好，我正在尝试写一个 [tun2ssh](https://github.com/LuoZijun/rust-netproxy) 的项目，大概就是 转发 `TAP` 的数据包至 `TUN` 设备，然后把 `TUN` 设备中的 `TCP/UDP` 数据包 通过 `SSH` 通道放在远程服务器执行，并传回。

项目目标旨在提高易用性，减少配置。争取做到 一行命令解决所有问题:

```bash
tun2ssh --ssh_host "20.202.20.20" --ssh_name "root" --ssh_password "impasswd!"
tun2ssh --ssh_host "20.202.20.20" --ssh_name "root" --ssh_pri_key "~/.ssh/my_pri_key"
```

由于刚开始，对 `TAP/TUN` 这块还不太熟悉，如果您代码这块可以很好工作起来，那将会极大地加速 `tun2ssh` 项目的开发进度。

目前看起来， 数据包（IPv4/IPv6/TCP/UDP）这方面好像还没有支持完善。

非常希望得到你的帮助。

**Comment by realityone** [comment]
tun/tap 相关可以直接参考 [rust-tun](https://github.com/meh/rust-tun)，因为该项目还不成熟，所以我直接抄来用了。

创建 tun 和创建 tap 的过程是很类似的。

**Comment by LuoZijun** [comment]
@realityone 好的，谢谢你的回复。

**Comment by LuoZijun** [comment]
@realityone 

对比后，决定还是使用你修改过的 `TUN` 代码 :)

你不考虑把这个功能分开放吗？这样我似乎可以直接引用，不需要复制。


https://github.com/LuoZijun/rust-netproxy/tree/master/taptun

**Comment by realityone** [comment]
之后会 pr 回 [rust-tun](https://github.com/meh/rust-tun)。

目前还不会分开，因为我不清楚对于一个 tun/tap lib 需要暴露哪些 API 才是合理的。
